timestep_respacing: '200'
skip_timesteps: 100

lp_custom: 1.0
lp_custom_value: 0.15
lpips_sim_lambda: 0
l2_sim_lambda: 0
l1_sim_lambda: 0
range_lambda: 0

deg_cone_projection: 30

clip_guidance_lambda: 0
classifier_lambda: 0.1

image_dir: 'samples_oct'
batch_size: 4

seed: 1

classifier_type: 1
second_classifier_type: 0
third_classifier_type: -1

use_blended: false

method: 'dvces'
gen_type: 'p_sample'

model_output_size: 256

enforce_same_norms: true

diffusion_checkpoint: 'ema_0.9999_270000_oct_v1'

config_base: 'oct.yml'


